DICT_LEADING = 'dictionaries/leading.json'
DICT_LAGGING = 'dictionaries/lagging.json'
DICT_LAGGING_REV = 'dictionaries/lagging-rev.json'
DICT_DIRECTIONALITY = 'dictionaries/directionality.json'
DICT_POSITIVE = 'dictionaries/positive.json'
DICT_NEGATIVE = 'dictionaries/negative.json'
DICT_LITIGIOUS = 'dictionaries/litigious.json'
DICT_UNCERTAINTY = 'dictionaries/uncertainty.json'

DS100 = 'datasets/ds100.json'
DS75 = 'datasets/ds75.json'
DS66 = 'datasets/ds66.json'
DS50 = 'datasets/ds50.json'

MODEL = 'models/model.json'